### ISSUE TITLE
TypeError: p is not a function

### ISSUE THREAD

**Issue by nicolad** [scio-labs/use-inkathon#17]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/1477453/226676172-99137fd8-0921-4bdb-a529-75adf9364306.png">

**Comment by wottpal** [comment]
Can you give a bit more context, @nicolad? Would be happy to solve this :) Never experienced it on my own.

**Comment by nicolad** [comment]
Hey @wottpal, don't remember now, it was last week 😅 
when I will be able to reproduce, will open with more details.

**Comment by melitus** [comment]
I experienced the same problem trying to run deploy smart contract to aleph testnet

**Comment by wottpal** [comment]
Hey @melitus, would love to help. Are you able to provide more info?

**Comment by wottpal** [comment]
Closing this until more info is provided.

**Comment by wottpal** [comment]
Closing this until more info is provided.

**Comment by pcfaktor** [comment]
Hi @wottpal !
I get this error when trying to add a custom contract. Tried with flipper and incrementer from ink-examples. Doing everything from the <link> section. Contracts are built normally. Greeter deploys fine. But when running my deploy_flipper I get:
```> @inkathon/contracts@0.8.0 deploy_flipper /home/pcfaktor/Projects/substrate/inkathon/contracts
> pnpm run script deploy_flipper


> @inkathon/contracts@0.8.0 script /home/pcfaktor/Projects/substrate/inkathon/contracts
> f() { tsx ./scripts/$1; }; f "$@" "deploy_flipper"

Initialized API on Development (0.41.0-120504a771e)
Initialized Account: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY (1,152,920.4837 Unit)

/home/pcfaktor/Projects/substrate/inkathon/node_modules/.pnpm/@scio-labs+use-inkathon@0.10.0_@nightlylabs+wallet-selector-polkadot@0.2.6_@polkadot+util@12._qn5wyinnt4bedqajjav3juyxfq/node_modules/@scio-labs/use-inkathon/src/helpers/unwrapResult.ts:29
}
^


TypeError: P is not a function
    at unwrappedResult (/home/pcfaktor/Projects/substrate/inkathon/node_modules/.pnpm/@scio-labs+use-inkathon@0.10.0_@nightlylabs+wallet-selector-polkadot@0.2.6_@polkadot+util@12._qn5wyinnt4bedqajjav3juyxfq/node_modules/@scio-labs/use-inkathon/src/helpers/unwrapResult.ts:29:1)
    at Generator.next (<anonymous>)
    at file:///home/pcfaktor/Projects/substrate/inkathon/node_modules/.pnpm/@scio-labs+use-inkathon@0.10.0_@nightlylabs+wallet-selector-polkadot@0.2.6_@polkadot+util@12._qn5wyinnt4bedqajjav3juyxfq/node_modules/@scio-labs/use-inkathon/dist/chunk-3AQ3E45C.js:1:629
    at new Promise (<anonymous>)
    at t (file:///home/pcfaktor/Projects/substrate/inkathon/node_modules/.pnpm/@scio-labs+use-inkathon@0.10.0_@nightlylabs+wallet-selector-polkadot@0.2.6_@polkadot+util@12._qn5wyinnt4bedqajjav3juyxfq/node_modules/@scio-labs/use-inkathon/dist/chunk-3AQ3E45C.js:1:445)
    at unwrappedResult (/home/pcfaktor/Projects/substrate/inkathon/node_modules/.pnpm/@scio-labs+use-inkathon@0.10.0_@nightlylabs+wallet-selector-polkadot@0.2.6_@polkadot+util@12._qn5wyinnt4bedqajjav3juyxfq/node_modules/@scio-labs/use-inkathon/src/helpers/unwrapResult.ts:29:1)
    at new Promise (<anonymous>)
    at unwrappedResult (/home/pcfaktor/Projects/substrate/inkathon/node_modules/.pnpm/@scio-labs+use-inkathon@0.10.0_@nightlylabs+wallet-selector-polkadot@0.2.6_@polkadot+util@12._qn5wyinnt4bedqajjav3juyxfq/node_modules/@scio-labs/use-inkathon/src/helpers/unwrapResult.ts:29:1)
    at Generator.next (<anonymous>)
    at file:///home/pcfaktor/Projects/substrate/inkathon/node_modules/.pnpm/@scio-labs+use-inkathon@0.10.0_@nightlylabs+wallet-selector-polkadot@0.2.6_@polkadot+util@12._qn5wyinnt4bedqajjav3juyxfq/node_modules/@scio-labs/use-inkathon/dist/chunk-3AQ3E45C.js:1:629

Node.js v18.17.0
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```
