### ISSUE TITLE
Lack of installation requirements

### ISSUE THREAD

**Issue by dellwatson** [scio-labs/use-inkathon#76]
```
pnpm add @scio-labs/use-inkathon
# or
npm install @scio-labs/use-inkathon
# or
yarn add @scio-labs/use-inkathon
```

installing the package module isn't enough (this is v0.10.0) because app will get this error:

```js
6:29:45 PM [vite] error while updating dependencies:
Error: Build failed with 6 errors:
node_modules/@scio-labs/use-inkathon/dist/chunk-6OTXFMWK.js:2:59: ERROR: Could not resolve "@polkadot/util"
node_modules/@scio-labs/use-inkathon/dist/chunk-6OTXFMWK.js:3:45: ERROR: Could not resolve "@polkadot/api-contract"
node_modules/@scio-labs/use-inkathon/dist/chunk-6OTXFMWK.js:4:53: ERROR: Could not resolve "@polkadot/api"
node_modules/@scio-labs/use-inkathon/dist/chunk-6OTXFMWK.js:5:32: ERROR: Could not resolve "@polkadot/util-crypto"
node_modules/@scio-labs/use-inkathon/dist/chunk-O4R6XJ2C.js:8:32: ERROR: Could not resolve "@polkadot/api-contract"
...
    at failureErrorWithLog (/Users/dellwatson/Desktop/hyape_1/starex_v2/node_modules/vite/node_modules/esbuild/lib/main.js:1650:15)
    at /Users/dellwatson/Desktop/hyape_1/starex_v2/node_modules/vite/node_modules/esbuild/lib/main.js:1058:25
    at /Users/dellwatson/Desktop/hyape_1/starex_v2/node_modules/vite/node_modules/esbuild/lib/main.js:1526:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ```
resulting unable to even run locally
even the current example your provide in react-ts folder also not working, i need to install nightlylabs too
 
 ```js
[ERROR] Could not resolve "@nightlylabs/wallet-selector-polkadot"

    node_modules/@scio-labs/use-inkathon/dist/chunk-R4LN4DEY.js:2:38:
      2 │ import { NightlyConnectAdapter } from '@nightlylabs/wallet-selector-polkadot';
        ╵                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@nightlylabs/wallet-selector-polkadot" as external to exclude it from the
  bundle, which will remove this error and leave the unresolved path in the bundle.

```

so need to install these dependecies
```js
    "@nightlylabs/wallet-selector-polkadot": "^0.2.6",
    "@polkadot/api": "^10.12.6",
    "@polkadot/api-contract": "^10.12.6",
    "@polkadot/util-crypto": "^12.6.2",
    "@scio-labs/use-inkathon": "^0.10.0",
    ```

**Comment by wottpal** [comment]
Thanks for reporting! Yes, you are right, depending on your package manager, peer dependencies need to be installed manually. **Which package manager were you using?**
